#Body Crits
b2 = ["Dismembered Arm", "The Dismembered Arm is gone. You drop any items in that dismembered arms hand immediately. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]
b3 = ["Dismembered Hand", "The Dismembered Hand is gone. You drop any items in the dismembered hand immediately. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]
b4 = ["Collapsed Lung", "-2 to MOVE (minimum 1) Base Death Save Penalty is increased by 1.", "Paramedic DV15", "Surgery DV15"]
b5 = ["Broken Ribs", "At the end of every Turn where you move further than 4m/yds on foot, you re-suffer this Critical Injury's Bonus Damage directly to your Hit Points.", "Paramedic DV13", "Paramedic DV15 or Surgery DV13"]
b6 = ["Broken Arm", "The Broken Arm cannot be used. You drop any items in that arm's hand immediately.", "Paramedic DV13", "Paramedic DV15 or Surgery DV13"]
b7 = ["Foreign Object", "At the end of every Turn where you move further than 4m/yds on foot, you re-suffer this Critical Injury's Bonus Damage directly to your Hit Points.", "First aid or Paramedic DV13", "Quick fix removes the injury permanently"]
b8 = ["Broken Leg", "-4 to MOVE (minimum 1)", "Paramedic DV13", "Paramedic DV15 or Surgery DV13"]
b9 = ["Torn Muscle", "-2 to Melee Attacks", "Paramedic DV13", "Quick fix removes the injury permanently"]
b10 = ["Spinal Injury", "Next Turn, you cannot take an Action, but you can still take a Move Action. Base Death Save Penalty is increased by 1.", "Paramedic DV15", "Surgery DV15"]
b11 = ["Crushed Fingers", "-4 to all Actions involving that hand", "Paramedic DV13", "Surgery DV15"]
b12 = ["Dismembered Leg", "The Dismembered Leg is gone. -6 to MOVE (minimum 1) You cannot dodge attacks. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]

#Head Crits
h2 = ["Lost Eye", "The Lost Eye is gone. -4 to Ranged Attacks & Perception Checks involving vision. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]
h3 = ["Brain Injury", "-2 to all Actions. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]
h4 = ["Damaged Eye", "-2 to Ranged Attacks & Perception Checks involving vision.", "Paramedic DV15", "Surgery DV13"]
h5 = ["Concussion", "-2 to all Actions", "First Aid or Paramedic DV13", "Quick Fix removes Injury Effect permanently"]
h6 = ["Broken Jaw", "-4 to all Actions involving speech", "Paramedic DV13", "Paramedic or Surgery DV13"]
h7 = ["Foreign Object", "At the end of every Turn where you move further than 4m/yds on foot, you re-suffer this Critical Injury's Bonus Damage directly to your Hit Points.", "First Aid or Paramedic DV13", "Quick Fix removes Injury Effect permanently"]
h8 = ["Whiplash", "Base Death Save Penalty is increased by 1.", "Paramedic DV13", "Paramedic or Surgery DV13"]
h9 = ["Cracked Skull", "Aimed Shots to your head multiply the damage that gets through your SP by 3 instead of 2. Base Death Save Penalty is increased by 1.", "Paramedic DV15", "Paramedic or Surgery DV15"]
h10 = ["Damaged Ear", "Whenever you move further than 4m/yds on foot in a Turn, you cannot take a Move Action on your next Turn. Additionally you take a -2 to Perception Checks involving hearing.", "Paramedic DV13", "Surgery DV13"]
h11 = ["Crushed Windpipe", "You cannot speak. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV15"]
h12 = ["Lost Ear", "The Lost Ear is gone. Whenever you move further than 4m/yds on foot in a Turn, you cannot take a Move Action on your next Turn. Additionally you take a -4 to Perception Checks involving hearing. Base Death Save Penalty is increased by 1.", "N/A", "Surgery DV17"]
